name = "minimal-blog"
description = "A minimal blog theme for Gutenberg"
license = "MIT"
homepage = "https://github.com/NuLL3rr0r/gutenberg-theme-minimal-blog"
min_version = "0.2"

[extra]
minimal_blog_excerpt_link = "Read more..."
minimal_blog_rtl = false

[author]
name = "Mohammad S. Babaei"
homepage = "https://www.babaei.net"
